spring:
  application:
    name: classification-service
  datasource:
    url: ${URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      function:
        definition: regProvider;predictModel;savePredictModel;trainingModel;saveNewStateInDB;newModel;saveModelInDB;
        bindings:
          regProvider-in-0: sharedQueue
          #trainingModel-in-0: general2
          #trainingModel-out-0: general4
          #saveNewStateInDB-in-0: general4
          #newModel-in-0: general2
          #newModel-out-0: general3
          #saveModelInDB-in-0: general3
          predictModel-in-0: general2
          predictModel-out-0: general5
          savePredictModel-in-0: general5
server:
  port: 8080

