spring:
  application:
    name: classification-service
  datasource:
    url: ${URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    password: {RABBITMQ_USER_USERNAME}
    username: {RABBITMQ_USER_PASSWORD}

  cloud:
    stream:
      function:
        definition: regProvider;predictModel;savePredictModel;newModel;saveModelInDB;trainingModel;saveNewStateInDB;
        bindings:
          regProvider-in-0: sharedQueue
          newModel-in-0: general2
          newModel-out-0: general3
          saveModelInDB-in-0: general3
          trainingModel-in-0: general2
          trainingModel-out-0: general4
          saveNewStateInDB-in-0: general4
          predictModel-in-0: general2
          predictModel-out-0: general5
          savePredictModel-in-0: general5
server:
  port: 8082
  error:
    include-stacktrace: never

